title: lee's-linux-notes
email:
# description: >- # this means to ignore newlines until "baseurl:"
#   My GitHub goodies
baseurl: "/linux-notes" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll
show_downloads: false

# title: Hacker theme
# description: Hacker is a theme for GitHub Pages.
# show_downloads: true
google_analytics:

theme: jekyll-theme-hacker

exclude: [docs, script, LICENSE, README.md, thumbnail.png]

# markdown: kramdown
kramdown:
  parse_block_html: true

collections:
  notes:
    output: true

callout_note: "> <span style=\"color: #3878fa\"><span style=\"font-size: 2em\">🛈</span> **Note**</span> "
callout_caution: "> <span style=\"color: #f9f1a5\"><span style=\"font-size: 2em\">⚠</span> **Caution**</span> "

inline_note: " <span style=\"color: #3878fa\">🛈 **Note:**</span> "
inline_caution: " <span style=\"color: #f9f1a5\">⚠ **Caution:**</span> "
